const products = [{
    id:  0, 
    name: "shirt1",
    price: 20.99,
    instock: 100,
    Description: "The best ___ you will find around",
    imgSrc: "images/pic1.jpg",
},
{
    id:  1, 
    name: "shirt2",
    price: 19.02,
    instock: 50,
    Description: "The best ___ you will find around",
    imgSrc: "images/pic2.jpg",
},
{
    id:  2, 
    name:"shirt3",
    price: 18.29,
    instock: 13,
    Description: "The best ___ you will find around",
    imgSrc: "images/pic3.jpg",
},
{
    id:  3, 
    name:"shirt4",
    price: 17.29,
    instock: 10,
    Description: "The best ___ you will find around",
    imgSrc: "images/pic5.jpg",
},
{
    id:  4, 
    name:"shirt5",
    price: 17.29,
    instock: 40,
    Description: "The best ___ you will find around",
    imgSrc: "images/pic6.jpg",
},
{
    id:  5, 
    name:"shirt6",
    price: 17.29,
    instock: 110,
    Description: "The best ___ you will find around",
    imgSrc: "images/pic7.jpg",
},
{
    id:  6, 
    name:"shirt7",
    price: 17.29,
    instock: 50,
    Description: "The best ___ you will find around",
    imgSrc: "images/pic8.jpg",
},
{
    id:  7, 
    name:"shirt8",
    price: 17.29,
    instock: 10,
    Description: "The best ___ you will find around",
    imgSrc: "images/pic4.jpg",
},
{
    id:  8, 
    name:"shirt9",
    price: 17.29,
    instock: 14,
    Description: "The best ___ you will find around",
    imgSrc: "images/pic4.jpg",
},

];